### ISSUE TITLE
[FEATURE] Create a contributing file

### ISSUE THREAD

**Issue by Bashamega** [Bashamega/ai-helper-tools#2]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Our repository is missing the contributing guide.

### Proposed Solution

We are looking for some one to write us a detailed contibuting.md file.

If you need help feel free to ask me.

### Do you want to work on this issue?

No

**Comment by Bridgetamana** [comment]
I want to work on this :)

**Comment by Bashamega** [comment]
> I want to work on this :)
> 

Great

**Comment by Bridgetamana** [comment]
I haven't created a contributing guide before, please can you help me with some pointers.

**Comment by Bashamega** [comment]
> I haven't created a contributing guide before, please can you help me with some pointers.

Sure. It is simply a file to tell the developer how to set up the project locally. You can check this for reference: https://github.com/Bashamega/WebDevTools/blob/main/contributing.md

**Comment by Bridgetamana** [comment]
Oh, Thanks.

**Comment by Bashamega** [comment]
Forgot to close this. Sorry.
