### ISSUE TITLE
[FEATURE] Integrate a dark mode

### ISSUE THREAD

**Issue by Bashamega** [Bashamega/ai-helper-tools#3]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

This repo was built on light mode, but we want to integrate a dark mode.

### Proposed Solution

We can use tailwind to add a dark mode

### Do you want to work on this issue?

No

**Comment by Rodney1988** [comment]
Hi! Can I work on this one?

**Comment by Bashamega** [comment]
> Hi! Can I work on this one? 

Sure

**Comment by Rodney1988** [comment]
It should be set
