### ISSUE TITLE
[FEATURE] Add my app

### ISSUE THREAD

**Issue by blazgocompany** [Bashamega/ai-helper-tools#7]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

N/A

### Proposed Solution

Can I add my own app to this site?

I'm actually developing an AI website called ai8labs (or just ai8) with Python and I'm looking to make it grow. 🌱 This seems to be a good place to do that. Also, as per your profile, it seems you're "looking to collaborate on help others," so maybe you could help me?

I apologize if this is irrelevant.

### Screenshots

n/a

### Do you want to work on this issue?

No

**Comment by Bashamega** [comment]
You can add tool. Also it is only in Next js. Not in python

**Comment by blazgocompany** [comment]
Ok, thanks!

**Comment by blazgocompany** [comment]
So, I only see the Gemini writing tool on your website. How can I add my tool? Do I create a PR?

**Comment by Bashamega** [comment]
> So, I only see the Gemini writing tool on your website. How can I add my tool? Do I create a PR?
> 
> > Also it is only in Next js. Not in python
> 
> I meant my app was coded in Python, not yours.

Yes, create a pr, but it has to be coded in Next js, since this is a Next JS app
